#!/bin/bash

PUBLIC_IP=$(oc-metadata --cached PUBLIC_IP_ADDRESS)

cat <<EOF
Hi Cloud Rider,
Welcome to the Virtualmin image!
Login at https://${PUBLIC_IP}:10000.
Login/password is root/{virtualmin_root_password}
MySQL is configured for user root with password {mysql_root_password}.
Enjoy!
EOF

